import sys
sys.path.insert(0, 'student_resource/code/business_entity_resolution')
import pandas as pd
from collections import Counter, defaultdict
from src.preprocessing import preprocess_dataframe
from src.candidate_generation import (
    InvertedCandidateIndex,
    generate_candidates_from_index,
    GENERIC_NAME_WORDS, GENERIC_ADDRESS_WORDS,
    extract_name_core, extract_address_numbers, extract_tokens
)

print("Loading data...")
s1 = preprocess_dataframe(pd.read_csv('smoke_data/s1_1000.tsv', sep='\t'))
s2 = preprocess_dataframe(pd.read_csv('smoke_data/s2_smoke.tsv', sep='\t'))
s3 = preprocess_dataframe(pd.read_csv('smoke_data/s3_smoke.tsv', sep='\t'))
gt = pd.read_csv('smoke_data/gt_1000.tsv', sep='\t')

true_pairs = set()
for row in gt.itertuples(index=False):
    for m in str(row.matched_entity_ids).split(','):
        m = m.strip()
        if m and m != 'nan':
            true_pairs.add((row.source1_entity_id, m))

index = InvertedCandidateIndex(max_bucket_size=500)
index.add_source(s2, 'S2')
index.add_source(s3, 'S3')
index.finalize()

cand_df_20 = generate_candidates_from_index(s1, index, top_k=20)
cand_pairs_20 = set(zip(cand_df_20['source1_entity_id'], cand_df_20['candidate_entity_id']))

cand_df_30 = generate_candidates_from_index(s1, index, top_k=30)
cand_pairs_30 = set(zip(cand_df_30['source1_entity_id'], cand_df_30['candidate_entity_id']))

cand_df_50 = generate_candidates_from_index(s1, index, top_k=50)
cand_pairs_50 = set(zip(cand_df_50['source1_entity_id'], cand_df_50['candidate_entity_id']))

cand_df_100 = generate_candidates_from_index(s1, index, top_k=100)
cand_pairs_100 = set(zip(cand_df_100['source1_entity_id'], cand_df_100['candidate_entity_id']))

s1_lkp = s1.set_index('entity_id')
s2_lkp = s2.set_index('entity_id')
s3_lkp = s3.set_index('entity_id')

all_missed_20 = [p for p in true_pairs if p not in cand_pairs_20]
genuinely_missed = []
not_in_pool = []
for s1_id, cid in all_missed_20:
    lkp = s2_lkp if cid.startswith('S2-') else s3_lkp
    if cid in lkp.index:
        genuinely_missed.append((s1_id, cid))
    else:
        not_in_pool.append((s1_id, cid))

print(f"Total true pairs: {len(true_pairs)}")
print(f"Total missed @20: {len(all_missed_20)}")
print(f"Not in smoke pool: {len(not_in_pool)}")
print(f"Genuinely missed in pool: {len(genuinely_missed)}")

# Let's inspect why each pair is missed
# Categories:
# 1. Country mismatch (different normalized country, blocked by country filter)
# 2. Ranking / Top-K fallout (retrieved / scored in index, but fell outside Top-20):
#    - would be found at @30
#    - would be found at @50
#    - would be found at @100
#    - generated by index candidate scoring but below top 100
# 3. No shared blocking key (never hit any inverted index bucket / blocking key):
#    - Name severe abbreviation / extreme variation / spelling mismatch
#    - Address only match but missing address numbers / no shared address token
#    - Empty / missing fields
# 4. Filtered / Pruned bucket (shared token was a high-frequency pruned token)

categories = defaultdict(list)

for s1_id, cid in genuinely_missed:
    s1r = s1_lkp.loc[s1_id]
    lkp = s2_lkp if cid.startswith('S2-') else s3_lkp
    cr = lkp.loc[cid]

    c1 = str(s1r['country_normalized']).strip().lower()
    c2 = str(cr['country_normalized']).strip().lower()
    n1 = str(s1r['business_name_normalized']).strip()
    n2 = str(cr['business_name_normalized']).strip()
    a1 = str(s1r['business_address_normalized']).strip()
    a2 = str(cr['business_address_normalized']).strip()
    
    pair_info = {
        's1_id': s1_id, 'cid': cid,
        's1_name': n1, 'cand_name': n2,
        's1_addr': a1, 'cand_addr': a2,
        's1_country': c1, 'cand_country': c2
    }

    if c1 != c2:
        categories['1. Country Mismatch'].append(pair_info)
    elif (s1_id, cid) in cand_pairs_30:
        categories['2. Ranking / Top-K (Found at K=30)'].append(pair_info)
    elif (s1_id, cid) in cand_pairs_50:
        categories['3. Ranking / Top-K (Found at K=50)'].append(pair_info)
    elif (s1_id, cid) in cand_pairs_100:
        categories['4. Ranking / Top-K (Found at K=100)'].append(pair_info)
    else:
        # Check if they share any blocking keys or why they missed
        tok1 = set(extract_tokens(n1, GENERIC_NAME_WORDS, 3))
        tok2 = set(extract_tokens(n2, GENERIC_NAME_WORDS, 3))
        addr1 = set(extract_tokens(a1, GENERIC_ADDRESS_WORDS, 4))
        addr2 = set(extract_tokens(a2, GENERIC_ADDRESS_WORDS, 4))
        num1 = set(extract_address_numbers(a1))
        num2 = set(extract_address_numbers(a2))
        
        shared_name_tokens = tok1 & tok2
        shared_addr_tokens = addr1 & addr2
        shared_nums = num1 & num2
        
        if shared_name_tokens:
            categories['5. Low Index Score / Pruned Name Token (>K=100)'].append(pair_info)
        elif shared_nums and shared_addr_tokens:
            categories['6. Low Index Score / Address Match Only (>K=100)'].append(pair_info)
        elif shared_nums:
            categories['7. Address Number Only Match (Different Name & Street)'].append(pair_info)
        elif not n1 or not n2 or not a1 or not a2:
            categories['8. Missing / Empty Field Data'].append(pair_info)
        else:
            categories['9. Severe Name/Address Variation (Zero Shared Keys)'].append(pair_info)

print("\n" + "="*70)
print("CATEGORIZATION OF 262 GENUINELY MISSED TRUE PAIRS")
print("="*70)
for cat, items in sorted(categories.items()):
    pct = len(items) / len(genuinely_missed) * 100
    print(f"{cat}: {len(items)} pairs ({pct:.1f}%)")

print("\n" + "="*70)
print("10 REPRESENTATIVE EXAMPLES ACROSS KEY CATEGORIES")
print("="*70)
count = 0
for cat, items in sorted(categories.items()):
    print(f"\n--- Category: {cat} (Total in category: {len(items)}) ---")
    for ex in items[:2]:
        count += 1
        print(f"[{count}] S1 ({ex['s1_id']}): Name='{ex['s1_name']}' | Addr='{ex['s1_addr']}' | Ctry='{ex['s1_country']}'")
        print(f"    Cand ({ex['cid']}): Name='{ex['cand_name']}' | Addr='{ex['cand_addr']}' | Ctry='{ex['cand_country']}'")
        if count >= 10:
            break
    if count >= 10:
        break
